version: '3.8'
services:
  bot-dev:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    depends_on:
      - postgres
      - pgadmin

  bot-prod:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    depends_on:
      - postgres
      - pgadmin

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    links:
      - postgres
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 5050:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - bot-postgres:/var/lib/postgresql/data

volumes:
  bot-postgres:
  pgadmin-data:
